version: '2.2'
services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - fbnet
  kafka:
    image: docker.io/bitnami/kafka:3.2
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - fbnet
  filebeat:
    image: elastic/filebeat:8.3.1
    container_name: filebeat
    command: --path.config=/usr/share/filebeat --strict.perms=false 
    volumes:
      - ./filebeat.docker.yml:/usr/share/filebeat/filebeat.yml
      - ./input:/var/log
      - ./output:/tmp
    depends_on:
      - kafka
    networks:
      - fbnet
volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
networks:
  fbnet:
    driver: bridge
