filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/*.log

#output.file:
#  path: "/tmp/filebeat"
#  filename: filebeat
#  codec.format:
#    string: '%{[message]}'

output.kafka:
  hosts: ["kafka:9092"]
  topic: 'fb_topic'
  partition.round_robin:
    reachable_only: false
  required_acks: 1
  compression: gzip
  max_message_bytes: 1000000
  codec.format:
    string: '%{[message]}'

filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

#processors:
#  - drop_fields:
#      fields: ["log","input","agent","ecs","host","@timestamp","metadata"]
